# Generated by Django 3.0.7 on 2020-06-17 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Item'),
        ),
    ]
