# Generated by Django 3.0.7 on 2020-06-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200622_1213'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Price',
        ),
    ]
