# Generated by Django 3.0.7 on 2020-06-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200627_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_saved',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
